### ISSUE TITLE
Masters>Branch>Add New Branch

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#10]
1. Phone Number - Need to represent the mandatory fields with an asterisk * symbol. It shouldn't accept the numbers less than or more than 10 digits as inputs.
2. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
3. Email - After entering an invalid email, it should highlighted with an alert message.
4. Email - Need to represent the mandatory fields with an asterisk * symbol.
5. Need to remove it in phone number

![Screenshot (62)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/0d158337-c701-499b-b386-1a6e1d999328)

6. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
7. Delete - After clicking on the delete icon, a pop up message should display on the page.
8. Add - Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Branch Added Successfully**.
9. Edit - Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Branch Updated Successfully**.
10. Status - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
8. Add - Spelling mistake is present in the word Sucessfully. Rename the toast message as Branch Added Successfully.
https://electcareapi.m8itsolutions.in/api/addBranch @Prabhu

**Comment by M8Balaji** [comment]
Status is not mandatory, Others were fixed

**Comment by M8Balaji** [comment]
For Delete pop up - Create a new issue, please label it as Enhancement

**Comment by Gokilavani-m8** [comment]
Rename the highlighted field as **Branch Name**

![Screenshot (128)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/3caa0818-4d10-4fe3-9f57-4667a2dfaa0d)

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
1. Rename the highlighted message as **Branch Name is Required**

![Screenshot (158)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/1b84c151-b61b-4503-ba06-a9d9f82fbbea)

2. Rename the highlighted message as **Branch Name can contain alphabets and spaces**

![Screenshot (159)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/710d5e12-844f-4865-957e-d549f1775924)

3. Email - It's accepting without an extension.com/.in. Need to set the validation properly.
4. Phone Number - It shouldn't accept special characters, alphabet, spaces & numbers less or more than 10 digits as inputs. While entering an invalid input, it should be highlighted with an alert message. No highlighted message has displayed.

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Bug#2 - Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
