### ISSUE TITLE
Jobcard Management>Edit>Print Receipt 

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#15]
After editing & updating the details and while clicking on Print Receipt, the receipt has shown the previous details. It shouldn't display the previous details. The receipt should modify accordingly for the details updated and show the recently updated details.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Print Receipt was removed, Not in Requirement

**Comment by Gokilavani-m8** [comment]
Pass
