### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#19]
There is no option to upload the profile picture

![Profile](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/c278b41b-c09d-40ae-a552-ca1caf3cebd3)

**Comment by M8Naveen** [comment]
There is no option in the web page. so please ignore the image attachment field as default icon.

**Comment by Gokilavani-m8** [comment]
Accepted
