### ISSUE TITLE
Job closed 

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#20]
The job closed count isn't gets updated for the closed jobs. By default the Job closed has shown as No Jobs Found. Need to change it

![e41bd679-83dd-4c49-8783-561b42a327ab](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/55a2a8b2-b97a-4feb-96f2-61d48dde8708)

![40f8e8ef-77a5-4b8f-863e-d2bfe4565566](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/8e0fbb65-1ae6-452e-8f59-89c52af5c039)

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by M8Naveen** [comment]
Please ignore

**Comment by Gokilavani-m8** [comment]
Pass
