### ISSUE TITLE
Attendance>Time

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#21]
1. In Time & Out Time - Need to change it as **PM** not **AM**

![attendance](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/9432005b-a058-4fab-9f8b-d43296c1c7dc)

2. Shift In & Shift Out - Need to change it as **PM** not **AM**

![2c3166f1-1a5e-4087-b39f-9f30667979c2](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/cf789649-4d41-410e-b486-ab9e77882f26)

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
