### ISSUE TITLE
Jobcard Management>Add New Jobcard>Product Details

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#24]
Need to highlight the message in red color

![Screenshot (76)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/3a79e7d2-4c77-4ace-b317-473ab0d16d2c)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
