### ISSUE TITLE
Job Details>Payment Detail

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#25]
1. There is no option to delete one of the image in payment details

![Job details](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/bf3c9f5c-24f3-47a5-9b3c-d27791fbaf74)

2. While uploading the receipt, without clicking on submit icon the image has been displayed on the Admin Panel>Joborder Management>View>Bill images. Need to fix it.
3. While uploading the receipt and clicking on submit icon, the image should be display on the admin panel>Joborder Management>View>Bill images.

**Comment by M8Naveen** [comment]
Not like that image is separate so ones uploaded it will be attached and submitted. Now add delete option so no need the image it can be delete to the list. Fixed

**Comment by Gokilavani-m8** [comment]
Pass
