### ISSUE TITLE
Jobcard Management>Add New Jobcard>Product Details

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#26]
1. While entering the product details, the messages have been displayed. Need to remove it.
2. After entering an invalid product details and clicking on the add icon, the highlighted message should be shown on the page.

![Screenshot (77)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/f307b365-b579-478a-978e-6e067cad8b63)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
