### ISSUE TITLE
Inventory Management>Item

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#27]
1. Rename the Product as **Item**.
2. Rename Add New Product as **Add New Item**.

![Screenshot (78)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/a7aaf0e0-7dd6-4863-be1b-9cc6fa00fbae)

3. Rename Add Product as **Add Item**.
4. Rename Back to Product List as **Back to Item List**.

![Screenshot (79)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/ffe2a83f-31bd-4548-8add-eb570a1e3d3d)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
