### ISSUE TITLE
Jobcard Management>Add New Jobcard>Add

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#28]
Address, Email, Mobile Number - Need to represent the mandatory fields with an asterisk * symbol for these fields.

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Email - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
Email Id is not mandatory field for this scenario @Gokilavani-m8

**Comment by Gokilavani-m8** [comment]
Pass
