### ISSUE TITLE
Job Details>Requirements>Service description

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#29]
Service description>Kebab Menu>Delete icon - While clicking on delete icon, it has been deleted but after refreshing the page it has showed on the page. Need to fix it.

https://github.com/Gokilavani-m8/Electo-care/assets/167422482/8433e8ce-7fc7-4af7-a0d9-098f51fbca41

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by M8Naveen** [comment]
Ones deleted the list then need to click the update button then only updated list will be show.

**Comment by Gokilavani-m8** [comment]
Pass
