### ISSUE TITLE
Inventory Management>Stock Status>Add

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#3]
1. After adding a new stock status and clicking on the add icon, a toast message has displayed but it is not visible in the stock status list page.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3.  After adding a new stock status and clicking on the add icon, a toast message should appear as **Stock Status Added Successfully**.

![Screenshot (50)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/9eb3d2b3-906d-40a9-ac5a-c27e1f12ff60)

4.  After editing a new stock status and clicking on the update icon, a toast message should appear as **Stock Status Updated Successfully**.
5. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
6. Spelling mistake is present in the word **Sucessfully**. Rename the toast message for both add and edit page.
7. Item - Need to represent the mandatory fields with an asterisk * symbol.
8. Status - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Toast messages will be check by Prabhu
Status not a mandatory field

**Comment by Gokilavani-m8** [comment]
1. After adding a new stock status and clicking on the add icon, a toast message has displayed but it is not visible in the stock status list page - Not Fixed
2. After adding a new stock status and clicking on the add icon, a toast message should appear as **Stock Status Added Successfully** Not as Quality Updated Successfully.
3. After editing a new stock status and clicking on the update icon, a toast message should appear as **Stock Status Updated Successfully** Not as Stock Updated Successfully.
4. While editing a stock status, the item has displayed in numbers. It should display the dropdown list properly

![Screenshot (167)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/b0e18ce0-852c-43d0-a9de-cfacb51fb4ae)

5. Quantity - While entering alphabets and special characters as input, it should be highlighted with an alert message. It shouldn't display as toast message

![Screenshot (166)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/29f28ee6-93ab-447d-9858-58c731718227)

**Comment by M8Balaji** [comment]
Point 4 - Because of old data, Delete it and Check with new data

**Comment by Gokilavani-m8** [comment]
Pass
