### ISSUE TITLE
Spare parts pending

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#31]
Need to display the spare parts pending on the page

![0a9707c0-9515-433d-bdd3-f325f83d2b34](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/69d78d2d-3bc3-4305-a0d1-236b4b683a5c)

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
