### ISSUE TITLE
Employee Management>Employee Activity

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#33]
Search & Select the Data Range - It's not working

![Screenshot (82)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/bb657b33-adfa-4b7e-aa44-103a9732bfc6)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Search - Not working

![Screenshot (101)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/8b4baffd-0bd1-482a-813d-9339e8acaf86)

Select the Data Range - Need to remove the highlighted portion. Only one date range is included

![Screenshot (103)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/51718b69-e93d-418e-84e9-d41dca117e5a)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Select the Data Range - Need to remove the highlighted portion. Only one date range is included

![image](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/69805d3a-0b5f-4fd5-90be-793013aa99f0)

**Comment by M8Balaji** [comment]
@Gokilavani-m8  Not an issue, For Identification purposes only

**Comment by Gokilavani-m8** [comment]
Select the Data Range - Not working
 
![Screenshot (145)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/7689ba87-9c17-4e31-b04d-9c8ffd6d7884)

![Screenshot (146)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/7b2b9d01-270d-40f9-904f-44a4e66611fd)

**Comment by Gokilavani-m8** [comment]
Pass
