### ISSUE TITLE
Job Details>Update Status>Spare Part Pending 

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#34]
1. Mobile App>Spare Part Pending - After entering the reason and total service charge, it should be shown in the Admin Panel>Joborder Management>View>Comments. It only shows the reason. It should display both the reason & total service charge.

**Comment by M8Naveen** [comment]
Please assign to admin panel. This is not in mobile end

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
