### ISSUE TITLE
Sales Report

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#35]
Paid & Unpaid Amount - Need to show the exact amount 

![Screenshot (116)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/814b5610-8e5d-46dd-908c-4dadf470df84)

**Comment by M8Balaji** [comment]
Prabhu will check this

**Comment by Gokilavani-m8** [comment]
There is no Coimbatore branch

![Screenshot (138)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/4466568a-34fd-4082-8b11-3b23cc03ac15)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass

**Comment by Gokilavani-m8** [comment]
__

**Comment by Gokilavani-m8** [comment]
Pass
