### ISSUE TITLE
Inventory Management>Stock Status

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#36]
1. Rename the Add as **Add New Stock Status**

![Screenshot (113)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/5d7fcf6b-a86e-4ded-87d8-b3634d614b9f)

2. Rename the Back to List as **Back to Stock Status List**

![Screenshot (114)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/25e886c8-165d-4725-8b9d-aa160436ea89)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
