### ISSUE TITLE
Contact Management>Add Contact

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#39]
After adding a new contact, the toast message has displayed. But in contact list page the new contact is not added. It should display the new contact on the list page

[Recording-20240620_231847.webm](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/a00b7636-8a20-42f0-9cfc-2862acdbcaed)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
