### ISSUE TITLE
Masters>Department>Add New Department

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#4]
1. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3. After adding a new department and clicking on the add icon, a toast message should appear as **Department Added Successfully**.
4. After editing a new department and clicking on the update icon, a toast message should appear as **Department Updated Successfully**.
5. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
6. Spelling mistake is present in the word **Sucessfully**. Rename the toast message for both add and edit page.
7. Status - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Module has Removed - Not in Requirement

**Comment by Gokilavani-m8** [comment]
Pass
