### ISSUE TITLE
Inventory Management>Stock Status>Add 

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#42]
1. After adding a new stock status and clicking on the add icon, a toast message should appear as **Stock Status Added Successfully** Not as Quality Updated Successfully.
2. After editing a new stock status and clicking on the update icon, a toast message should appear as **Stock Status Updated Successfully** Not as Stock Updated Successfully.
3. Need to remove the highlighted portion in drop down list, only three items are visible in stock status list page

![Screenshot (202)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/162f52c2-dd5f-4baa-8c7a-acd9aa94ca03)

**Comment by M8Balaji** [comment]
![Screenshot (62)](https://github.com/Gokilavani-m8/Electo-care/assets/150112780/11fad255-f3a2-4ca5-9848-75c5e37abce7)
3 - point  --- Can't able to re create the issue - working fine

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Bug#1,2 - Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
