### ISSUE TITLE
Masters>Contact Category>Add New

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#5]
1. The toast message should appear as **Contact Category Added Successfully**. Need some space in between the word **ContactCategory**.

![Screenshot (51)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/003599a0-b897-4d95-938d-a95f4ef160ce)

2. The toast message should appear as **Contact Category Updated Successfully**. First letter should be capital.

![Screenshot (52)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/1c71f7ce-c667-4887-9fc1-c425b1a528f7)
3.  Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
4. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
5. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
6. Status - Need to represent the mandatory fields with an asterisk * symbol.
7. Description - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Module has Removed - Not in Requirement

**Comment by Gokilavani-m8** [comment]
Pass
