### ISSUE TITLE
Masters>Product>Add New Product

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#6]
1. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
4. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Product Added Successfully**.
5. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Product Updated Successfully**.
6. Status - Need to represent the mandatory fields with an asterisk * symbol.
7. Description - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
2 point - Crete new issue and label it as Enhancement
6, 7 point - Not a mandatory field

**Comment by Gokilavani-m8** [comment]
1. After adding a new product and clicking on the add icon, a toast message should appear as Product Added Successfully Not as System Type Created Successfully.
2. After updating a new product and clicking on the update icon, a toast message should appear as Product Updated Successfully Not as System Type Updated Successfully.

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
