### ISSUE TITLE
Masters>Brand>Add New Brand

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#7]
1. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
4. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Brand Added Successfully**.
5. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Brand Updated Successfully**.
6. Status - Need to represent the mandatory fields with an asterisk * symbol.
7. Description - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
2 point - Crete new issue and label it as Enhancement
6, 7 point - Not a mandatory field

**Comment by Gokilavani-m8** [comment]
Pass
