### ISSUE TITLE
Masters>Complaint Type>Add New Complaint

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#8]
1. Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
4. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Complaint Type Added Successfully**.
5. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Complaint Type Updated Successfully**.
6. Need some space in between the words **Complaint Type**

![Screenshot (55)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/2b49478b-6e71-42ba-843f-98ad847bd670)

8. After editing a new complaint type and clicking on the update icon, a toast message should appear as **Complaint Type Updated Successfully**.
9. Status - Need to represent the mandatory fields with an asterisk * symbol.
10. Description - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Module has Removed - Not in Requirement

**Comment by Gokilavani-m8** [comment]
Pass
