### ISSUE TITLE
Branch Management>Add Branch Admin

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#9]
1. Password - Need to represent eye icon in password.
2. Need to change the allignment in branch admins list page

![Screenshot (60)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/56262d66-7d51-4947-903f-7dfa4c2d0e97)

3. Delete - Delete icon not working.
4. While editing the branch admin, password should be shown. It shouldn't be blank.
5. Update - After editing the branch admin and clicking on the update icon, a toast message should appear as **Branch Admin Added Successfully**. Update icon not working.
6. Add - After adding new branch admin and clicking on add icon, it doesn't display in branch admin list. Need to display it.
7. After adding a new branch name, a toast message should appear as **Branch Admin Added Successfully**.
8. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
9. Status - Need to represent the mandatory fields with an asterisk * symbol.
10. Branch - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
4,5, 8 Point - Not as requirement, So the Update option removed
3, 6, 7 - Prabhu will fix
9 - not a mandatory field

**Comment by Gokilavani-m8** [comment]
The username is not displayed in branch admin list page

![Screenshot (127)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/e744d937-9e60-4ae2-b019-1f1f5326643f)

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
1. Phone Number - While entering the alphabets or special characters as inputs, it should be highlighted with an alert message. It shouldn't display as toast message.
2. First Name - While entering the numbers or special characters as inputs, it should be highlighted with an alert message. It shouldn't display as toast message.
3. Last Name - While entering the numbers or special characters as inputs, it should be highlighted with an alert message. It shouldn't display as toast message.
4. Email - It shouldn't accept without an extension.com/.in. While entering invalid email as inputs, it should be highlighted with an alert message. It shouldn't display as toast message.

![Screenshot (157)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/53beb347-631f-4395-93a8-00110523ef74)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
1. Rename the highlighted field as **Last Name can only contain alphabets and spaces**

![Screenshot (182)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/743b8527-f16e-47ee-a809-f5edc4fde693)

2. Phone No - While entering more than 10 numbers as input, it should be highlighted with alert message. It shouldn't display as toast message

![Screenshot (183)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/4a105c07-a1e7-485d-b8ec-73dba9346ac7)

3. Email & Phone No - While entering already existing email & Phone no, it should be highlighted with alert message. It shouldn't display as toast message

![Screenshot (184)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/399c1368-1f38-422e-9a54-613753a1339d)

**Comment by M8Balaji** [comment]
3 point - Currently not required

**Comment by Gokilavani-m8** [comment]
Pass
